---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: azure-cloud-provider:azure-cloud-provider
  namespace: kube-system
roleRef:
  kind: Role
  name: azure-cloud-provider
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    namespace: kube-system
    name: azure-cloud-provider
